#!/bin/bash
# Cortex Hub — Git Hooks Setup for Mixed-Language Projects
# Reads .cortex/project-profile.json (or .forgewright/project-profile.json)
# and generates a lefthook.yml with per-language glob filters.
#
# Usage: bash scripts/setup-hooks.sh [path-to-project-profile.json]
#
# Works on macOS and Linux. Requires: python3 (for JSON parsing), lefthook (installed if missing).

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

PROFILE_PATH="${1:-}"

# Auto-detect profile path if not provided
if [ -z "$PROFILE_PATH" ]; then
    if [ -f ".cortex/project-profile.json" ]; then
        PROFILE_PATH=".cortex/project-profile.json"
    elif [ -f ".forgewright/project-profile.json" ]; then
        PROFILE_PATH=".forgewright/project-profile.json"
    else
        echo -e "${RED}>>> Error: No project-profile.json found.${NC}"
        exit 1
    fi
fi

if [ ! -f "$PROFILE_PATH" ]; then
    echo -e "${RED}>>> Error: Profile not found at ${PROFILE_PATH}${NC}"
    exit 1
fi

echo -e "${BLUE}>>> Reading project profile from ${PROFILE_PATH}...${NC}"

# ─── Extract language/stack info using python3 (cross-platform) ──────────────
# We parse the profile to detect which languages/stacks are present.
# A "mixed" project has multiple distinct language ecosystems.

LANG_INFO=$(python3 -c "
import json, sys

with open('${PROFILE_PATH}', 'r') as f:
    profile = json.load(f)

fingerprint = profile.get('fingerprint', {})
stacks = profile.get('stacks', [])
languages = profile.get('languages', [])

# Normalize: collect all language identifiers
all_langs = set()

# From fingerprint.language (can be string or list)
lang_field = fingerprint.get('language', '')
if isinstance(lang_field, list):
    all_langs.update(l.lower() for l in lang_field)
elif lang_field:
    all_langs.add(lang_field.lower())

# From top-level stacks array
for s in stacks:
    if isinstance(s, dict):
        name = s.get('language', s.get('name', '')).lower()
        if name:
            all_langs.add(name)
    elif isinstance(s, str):
        all_langs.add(s.lower())

# From top-level languages array
for l in languages:
    if isinstance(l, str):
        all_langs.add(l.lower())

# Also check fingerprint.lint_tool for hints
lint_tool = fingerprint.get('lint_tool', '')

# Determine if mixed
is_mixed = len(all_langs) > 1

# Map languages to categories
categories = set()
lang_map = {
    'typescript': 'node', 'javascript': 'node', 'node': 'node',
    'python': 'python', 'py': 'python',
    'csharp': 'dotnet', 'c#': 'dotnet', 'dotnet': 'dotnet', 'fsharp': 'dotnet',
    'rust': 'rust', 'go': 'go', 'golang': 'go',
    'java': 'java', 'kotlin': 'java',
    'ruby': 'ruby',
}
for lang in all_langs:
    cat = lang_map.get(lang, lang)
    categories.add(cat)

# If only one language detected but stacks suggest more, still treat as potentially mixed
print(f\"LANGS={'|'.join(sorted(all_langs))}\")
print(f\"CATEGORIES={'|'.join(sorted(categories))}\")
print(f\"IS_MIXED={'true' if is_mixed else 'false'}\")
print(f\"LINT_TOOL={lint_tool}\")
")

# Parse the output into shell vars
eval "$(echo "$LANG_INFO" | sed 's/^/export /')"

echo -e "${BLUE}>>> Detected languages: ${LANGS}${NC}"
echo -e "${BLUE}>>> Categories: ${CATEGORIES}${NC}"
echo -e "${BLUE}>>> Mixed project: ${IS_MIXED}${NC}"

# ─── Install lefthook if not present ─────────────────────────────────────────
if ! command -v lefthook >/dev/null 2>&1; then
    echo -e "${YELLOW}>>> lefthook not found. Installing...${NC}"
    if command -v npm >/dev/null 2>&1; then
        npm install -g @evilmartians/lefthook 2>/dev/null || npm install -g lefthook 2>/dev/null || true
    elif command -v brew >/dev/null 2>&1; then
        brew install lefthook 2>/dev/null || true
    fi
    if ! command -v lefthook >/dev/null 2>&1; then
        echo -e "${RED}>>> Warning: Could not install lefthook automatically.${NC}"
        echo -e "${RED}>>> Install manually: https://github.com/evilmartians/lefthook${NC}"
    fi
fi

# ─── Generate lefthook.yml ───────────────────────────────────────────────────
LEFTHOOK_FILE="lefthook.yml"

echo -e "${BLUE}>>> Generating ${LEFTHOOK_FILE}...${NC}"

# Start with header
cat > "$LEFTHOOK_FILE" << 'HEADER'
# Auto-generated by Cortex Hub setup-hooks.sh
# Configures pre-commit hooks with per-language file filters for mixed projects.
# Re-run `bash scripts/setup-hooks.sh` to regenerate.

HEADER

# Build the pre-commit section
{
    echo "pre-commit:"
    echo "  parallel: true"
    echo "  commands:"

    # ── Node/TypeScript ──
    if echo "$CATEGORIES" | grep -q "node"; then
        cat << 'NODE_BLOCK'
    eslint:
      glob: "*.{ts,tsx,js,jsx}"
      run: npx eslint --fix {staged_files}
      stage_fixed: true
    prettier:
      glob: "*.{ts,tsx,js,jsx,json,md,css,yml,yaml}"
      run: npx prettier --write {staged_files}
      stage_fixed: true
NODE_BLOCK
    fi

    # ── Python ──
    if echo "$CATEGORIES" | grep -q "python"; then
        cat << 'PYTHON_BLOCK'
    python-lint:
      glob: "*.py"
      run: |
        if command -v ruff >/dev/null 2>&1; then
          ruff check --fix {staged_files}
        elif command -v flake8 >/dev/null 2>&1; then
          flake8 {staged_files}
        else
          echo "No Python linter found (ruff or flake8). Skipping."
        fi
      stage_fixed: true
    python-format:
      glob: "*.py"
      run: |
        if command -v ruff >/dev/null 2>&1; then
          ruff format {staged_files}
        elif command -v black >/dev/null 2>&1; then
          black {staged_files}
        else
          echo "No Python formatter found. Skipping."
        fi
      stage_fixed: true
PYTHON_BLOCK
    fi

    # ── .NET / C# ──
    if echo "$CATEGORIES" | grep -q "dotnet"; then
        cat << 'DOTNET_BLOCK'
    dotnet-build:
      glob: "*.{cs,csproj,sln,fs,fsproj}"
      run: dotnet build --no-restore
    dotnet-format:
      glob: "*.{cs,fs}"
      run: dotnet format --include {staged_files} --no-restore
      stage_fixed: true
DOTNET_BLOCK
    fi

    # ── Rust ──
    if echo "$CATEGORIES" | grep -q "rust"; then
        cat << 'RUST_BLOCK'
    rust-check:
      glob: "*.rs"
      run: cargo check
    rust-fmt:
      glob: "*.rs"
      run: cargo fmt -- --check
RUST_BLOCK
    fi

    # ── Go ──
    if echo "$CATEGORIES" | grep -q "go"; then
        cat << 'GO_BLOCK'
    go-vet:
      glob: "*.go"
      run: go vet ./...
    go-fmt:
      glob: "*.go"
      run: gofmt -l -w {staged_files}
      stage_fixed: true
GO_BLOCK
    fi

    # ── Universal: markdown/json/yaml prettier (if no node stack handles it) ──
    if ! echo "$CATEGORIES" | grep -q "node"; then
        cat << 'UNIVERSAL_BLOCK'
    format-docs:
      glob: "*.{json,md,yml,yaml}"
      run: |
        if command -v prettier >/dev/null 2>&1; then
          prettier --write {staged_files}
        else
          echo "Prettier not available. Skipping doc formatting."
        fi
      stage_fixed: true
UNIVERSAL_BLOCK
    fi

} >> "$LEFTHOOK_FILE"

# ── Pre-push section (heavier checks) ──
{
    echo ""
    echo "pre-push:"
    echo "  parallel: true"
    echo "  commands:"

    if echo "$CATEGORIES" | grep -q "node"; then
        cat << 'NODE_PUSH'
    typecheck:
      glob: "*.{ts,tsx}"
      run: npx tsc --noEmit
NODE_PUSH
    fi

    if echo "$CATEGORIES" | grep -q "python"; then
        cat << 'PYTHON_PUSH'
    python-typecheck:
      glob: "*.py"
      run: |
        if command -v mypy >/dev/null 2>&1; then
          mypy {push_files}
        elif command -v pyright >/dev/null 2>&1; then
          pyright {push_files}
        else
          echo "No Python type checker found. Skipping."
        fi
PYTHON_PUSH
    fi

    if echo "$CATEGORIES" | grep -q "dotnet"; then
        cat << 'DOTNET_PUSH'
    dotnet-test:
      glob: "*.{cs,fs}"
      run: dotnet test --no-build
DOTNET_PUSH
    fi

} >> "$LEFTHOOK_FILE"

echo -e "${GREEN}>>> Generated ${LEFTHOOK_FILE} with language-specific glob filters.${NC}"

# ─── Generate pyproject.toml for Python projects (if not present) ────────────
if echo "$CATEGORIES" | grep -q "python"; then
    if [ ! -f "pyproject.toml" ] && [ ! -f ".flake8" ] && [ ! -f "setup.cfg" ]; then
        echo -e "${BLUE}>>> Generating pyproject.toml with Python linter config...${NC}"
        cat > "pyproject.toml" << 'PYPROJECT'
# Auto-generated by Cortex Hub setup-hooks.sh
# Python linter/formatter configuration for mixed-language projects.

[tool.ruff]
# Only lint .py files (default), ignore non-Python files
target-version = "py311"
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
ignore = ["E501"]  # line-too-long handled by formatter

# Per-directory overrides: exclude non-Python directories
[tool.ruff.lint.per-file-ignores]
"*.md" = ["ALL"]
"*.json" = ["ALL"]
"*.yml" = ["ALL"]
"*.yaml" = ["ALL"]

[tool.ruff.format]
quote-style = "double"

[tool.flake8]
max-line-length = 120
exclude = ["*.md", "*.json", "*.yml", "*.yaml", "*.cs", "*.csproj", "node_modules", ".git", "__pycache__", "*.egg-info"]
extend-ignore = ["E501"]

[tool.black]
line-length = 120
target-version = ["py311"]
PYPROJECT
        echo -e "${GREEN}>>> Created pyproject.toml with Python config.${NC}"
    else
        echo -e "${BLUE}>>> Python config already exists. Skipping pyproject.toml generation.${NC}"
    fi
fi

# ─── Install lefthook hooks into .git ────────────────────────────────────────
if command -v lefthook >/dev/null 2>&1; then
    echo -e "${BLUE}>>> Installing lefthook git hooks...${NC}"
    lefthook install
    echo -e "${GREEN}>>> lefthook hooks installed successfully.${NC}"
else
    echo -e "${YELLOW}>>> Skipping lefthook install (not in PATH). Install lefthook and run 'lefthook install'.${NC}"
fi

echo -e "${GREEN}>>> Hook setup complete for ${IS_MIXED} mixed-language project.${NC}"
